### ISSUE TITLE
Misleading usage of the words "encrypt" and "decrypt"

### ISSUE THREAD

**Issue by Burrito-Bazooka** [the2f/Cryptii#2]
In many places in this project, the words "encrypt" and "decrypt" are being used where "encode" and "decode" should be used. This misusage should not be taken lightly - novice users may be mislead to think that this is a secure way of storing information, when it can be easily converted back without any key. Moreover, misconceptions are spread over what encryption, decryption, and cryptography actually are.

**Comment by panchr** [comment]
+1. This should not be called encryption as it is just misleading public users about what these terms mean.

**Comment by gabriel** [comment]
If you want to encrypt or decrypt please see: 
https://github.com/jedisct1/libsodium
https://download.libsodium.org/doc/

Do not use this project for anything real!

**Comment by Burrito-Bazooka** [comment]
Looks like it was fixed on the site. Closing.
